"""Informational alerts when a driver breaks the tenant's meal/hours policy --
generated by shifts.py::_check_driver_policy, never blocking the event that
triggered them. Same pattern as alarms.py (list + acknowledge), but on a
regular table (driver_shift_alerts, standard RLS), not a hypertable."""
from __future__ import annotations

import uuid

from fastapi import APIRouter, Depends, HTTPException, Query, status
from psycopg import AsyncConnection

from ..deps import get_db, require_non_driver
from ..schemas import DriverShiftAlertOut, Page
from ..security import TokenClaims

router = APIRouter(prefix="/driver-shift-alerts", tags=["driver-shift-alerts"])

_SELECT_COLUMNS = """a.id, a.driver_id, d.name, a.alert_type, a.details, a.occurred_at, a.acknowledged_at"""
_FROM_JOIN = "FROM driver_shift_alerts a JOIN drivers d ON d.id = a.driver_id"


@router.get("", response_model=Page[DriverShiftAlertOut])
async def list_driver_shift_alerts(
    conn: AsyncConnection = Depends(get_db),
    _: TokenClaims = Depends(require_non_driver),
    unacknowledged_only: bool = Query(False),
    limit: int = Query(50, ge=1, le=500),
    offset: int = Query(0, ge=0),
) -> Page[DriverShiftAlertOut]:
    where = "WHERE a.acknowledged_at IS NULL" if unacknowledged_only else ""
    total_row = await (await conn.execute(f"SELECT count(*) {_FROM_JOIN} {where}")).fetchone()
    total = total_row[0] if total_row else 0
    rows = await (
        await conn.execute(
            f"SELECT {_SELECT_COLUMNS} {_FROM_JOIN} {where} ORDER BY a.occurred_at DESC LIMIT %s OFFSET %s",
            (limit, offset),
        )
    ).fetchall()
    items = [
        DriverShiftAlertOut(
            id=r[0],
            driver_id=r[1],
            driver_name=r[2],
            alert_type=r[3],
            details=r[4],
            occurred_at=r[5].isoformat(),
            acknowledged_at=r[6].isoformat() if r[6] else None,
        )
        for r in rows
    ]
    return Page(items=items, total=total, limit=limit, offset=offset)


@router.post("/{alert_id}/acknowledge", status_code=status.HTTP_204_NO_CONTENT, response_model=None)
async def acknowledge_driver_shift_alert(
    alert_id: uuid.UUID,
    conn: AsyncConnection = Depends(get_db),
    user: TokenClaims = Depends(require_non_driver),
) -> None:
    row = await (
        await conn.execute(
            """UPDATE driver_shift_alerts SET acknowledged_at = now(), acknowledged_by = %s
               WHERE id = %s AND acknowledged_at IS NULL
               RETURNING id""",
            (user.user_id, alert_id),
        )
    ).fetchone()
    if row is None:
        # RLS (other tenant), already acknowledged, or missing -- same generic
        # 404 in all three cases, like acknowledge_alarm.
        raise HTTPException(status.HTTP_404_NOT_FOUND, "alert not found")
