"""Billing -- promotions (tenant_promotions) + invoices
(invoices/invoice_line_items) generated by the generate_invoices PROCEDURE
(0021_billing_invoices.sql). Core concerns: the price snapshot is real
(changing a plan's price AFTER invoicing must not alter an already issued
invoice), promotions only apply inside their window, and tenant isolation
of invoices/invoice_line_items -- unlike billing_plans/tenant_promotions,
invoices ARE readable by the tenant's own tenant_admin (the basis of "My
billing"), so this also tests that read RLS works in that direction, not
only that it blocks."""
import uuid
from datetime import date, timedelta

import pytest

from conftest import TEST_PASSWORD, auth_header, login

pytestmark = pytest.mark.asyncio


async def _create_plan(client, token, unit_price=190.0, category="gps"):
    resp = await client.post(
        "/billing/plans",
        json={
            "name": f"Plan {uuid.uuid4().hex[:6]}",
            "sku": f"SKU-{uuid.uuid4().hex[:8]}",
            "category": category,
            "unit_price": unit_price,
            "currency": "MXN",
            "billing_period": "monthly",
        },
        headers=auth_header(token),
    )
    assert resp.status_code == 201, resp.text
    return resp.json()


async def _subscribe(
    client, token, tenant_id, plan_id=None, quantity=1, unit_price_override=None, custom_description=None, category=None
):
    body = {"tenant_id": str(tenant_id), "quantity": quantity}
    if plan_id is not None:
        body["billing_plan_id"] = plan_id
    if custom_description is not None:
        body["custom_description"] = custom_description
        # category is required on a line without a plan. Default 'addon' here
        # because these billing tests use custom lines for generic cases
        # (installation, precision overflow) that do not represent a real device
        # -- a caller that needs another category passes it explicitly.
        body["category"] = category or "addon"
    if unit_price_override is not None:
        body["unit_price_override"] = unit_price_override
    resp = await client.post("/billing/subscription-items", json=body, headers=auth_header(token))
    assert resp.status_code == 201, resp.text
    return resp.json()


async def _run_invoice_job(pool):
    from app import db as db_module

    async with db_module.tenant_scoped_connection(pool, tenant_id=None, bypass=True) as conn:
        await conn.execute("CALL generate_invoices(0, '{}'::jsonb)")


# ---------------------------------------------------------------------------
# generate_invoices: bootstrap, snapshot, promotions
# ---------------------------------------------------------------------------

async def test_new_subscription_bootstraps_and_bills_immediately(client, two_tenants, platform_users, pool):
    token = await login(client, platform_users["super_admin"]["email"])
    plan = await _create_plan(client, token, unit_price=190.0)
    tenant_id = two_tenants["a"]["tenant_id"]
    await _subscribe(client, token, tenant_id, plan_id=plan["id"], quantity=3)

    await _run_invoice_job(pool)

    resp = await client.get("/billing/invoices", params={"tenant_id": str(tenant_id)}, headers=auth_header(token))
    assert resp.status_code == 200
    items = resp.json()["items"]
    assert len(items) == 1
    invoice = items[0]
    assert invoice["subtotal"] == 570.0  # 3 * 190
    assert invoice["discount_total"] == 0.0
    assert invoice["total"] == 570.0
    assert invoice["status"] == "issued"
    assert len(invoice["line_items"]) == 1
    assert invoice["line_items"][0]["quantity"] == 3
    assert invoice["line_items"][0]["unit_price"] == 190.0


async def test_price_change_after_invoice_does_not_alter_it(client, two_tenants, platform_users, pool):
    """Core requirement: invoice_line_items is a SNAPSHOT, never a live
    reference to billing_plans."""
    token = await login(client, platform_users["super_admin"]["email"])
    plan = await _create_plan(client, token, unit_price=200.0)
    tenant_id = two_tenants["a"]["tenant_id"]
    await _subscribe(client, token, tenant_id, plan_id=plan["id"], quantity=1)

    await _run_invoice_job(pool)

    await client.patch(f"/billing/plans/{plan['id']}", json={"unit_price": 999.0}, headers=auth_header(token))

    resp = await client.get("/billing/invoices", params={"tenant_id": str(tenant_id)}, headers=auth_header(token))
    invoice = resp.json()["items"][0]
    assert invoice["subtotal"] == 200.0
    assert invoice["line_items"][0]["unit_price"] == 200.0


async def test_full_waiver_promotion_zeroes_invoice_and_marks_paid(client, two_tenants, platform_users, pool):
    token = await login(client, platform_users["super_admin"]["email"])
    plan = await _create_plan(client, token, unit_price=500.0)
    tenant_id = two_tenants["a"]["tenant_id"]
    await _subscribe(client, token, tenant_id, plan_id=plan["id"], quantity=1)

    today = date.today()
    promo = await client.post(
        "/billing/promotions",
        json={
            "tenant_id": str(tenant_id),
            "description": "1 year free, pilot customer",
            "starts_at": today.isoformat(),
            "ends_at": (today + timedelta(days=365)).isoformat(),
            "discount_type": "full_waiver",
        },
        headers=auth_header(token),
    )
    assert promo.status_code == 201, promo.text

    await _run_invoice_job(pool)

    resp = await client.get("/billing/invoices", params={"tenant_id": str(tenant_id)}, headers=auth_header(token))
    invoice = resp.json()["items"][0]
    assert invoice["subtotal"] == 500.0
    assert invoice["discount_total"] == 500.0
    assert invoice["total"] == 0.0
    assert invoice["status"] == "paid"


async def test_percentage_promotion_discounts_correctly(client, two_tenants, platform_users, pool):
    token = await login(client, platform_users["super_admin"]["email"])
    plan = await _create_plan(client, token, unit_price=400.0)
    tenant_id = two_tenants["a"]["tenant_id"]
    await _subscribe(client, token, tenant_id, plan_id=plan["id"], quantity=1)

    today = date.today()
    await client.post(
        "/billing/promotions",
        json={
            "tenant_id": str(tenant_id),
            "description": "20% discount",
            "starts_at": today.isoformat(),
            "ends_at": (today + timedelta(days=30)).isoformat(),
            "discount_type": "percentage",
            "discount_value": 20,
        },
        headers=auth_header(token),
    )

    await _run_invoice_job(pool)

    resp = await client.get("/billing/invoices", params={"tenant_id": str(tenant_id)}, headers=auth_header(token))
    invoice = resp.json()["items"][0]
    assert invoice["subtotal"] == 400.0
    assert invoice["discount_total"] == 80.0
    assert invoice["total"] == 320.0
    assert invoice["status"] == "issued"


async def test_expired_promotion_not_applied(client, two_tenants, platform_users, pool):
    token = await login(client, platform_users["super_admin"]["email"])
    plan = await _create_plan(client, token, unit_price=300.0)
    tenant_id = two_tenants["a"]["tenant_id"]
    await _subscribe(client, token, tenant_id, plan_id=plan["id"], quantity=1)

    today = date.today()
    await client.post(
        "/billing/promotions",
        json={
            "tenant_id": str(tenant_id),
            "description": "old promo, already ended",
            "starts_at": (today - timedelta(days=60)).isoformat(),
            "ends_at": (today - timedelta(days=30)).isoformat(),
            "discount_type": "full_waiver",
        },
        headers=auth_header(token),
    )

    await _run_invoice_job(pool)

    resp = await client.get("/billing/invoices", params={"tenant_id": str(tenant_id)}, headers=auth_header(token))
    invoice = resp.json()["items"][0]
    assert invoice["discount_total"] == 0.0
    assert invoice["total"] == 300.0
    assert invoice["status"] == "issued"


async def test_tenant_without_active_items_gets_no_invoice(client, two_tenants, platform_users, pool):
    token = await login(client, platform_users["super_admin"]["email"])
    plan = await _create_plan(client, token, unit_price=150.0)
    tenant_id = two_tenants["a"]["tenant_id"]
    item = await _subscribe(client, token, tenant_id, plan_id=plan["id"], quantity=1)

    # The only line is cancelled BEFORE the job runs for the first time.
    await client.patch(f"/billing/subscription-items/{item['id']}", json={"end_now": True}, headers=auth_header(token))

    await _run_invoice_job(pool)

    resp = await client.get("/billing/invoices", params={"tenant_id": str(tenant_id)}, headers=auth_header(token))
    assert resp.json()["items"] == []


async def test_custom_line_without_plan_billed_with_own_description(client, two_tenants, platform_users, pool):
    token = await login(client, platform_users["super_admin"]["email"])
    tenant_id = two_tenants["a"]["tenant_id"]
    await _subscribe(client, token, tenant_id, custom_description="Initial installation", unit_price_override=800.0, quantity=1)

    await _run_invoice_job(pool)

    resp = await client.get("/billing/invoices", params={"tenant_id": str(tenant_id)}, headers=auth_header(token))
    invoice = resp.json()["items"][0]
    assert invoice["line_items"][0]["description"] == "Initial installation"
    assert invoice["line_items"][0]["unit_price"] == 800.0


# ---------------------------------------------------------------------------
# Access and isolation
# ---------------------------------------------------------------------------

async def test_numeric_overflow_for_one_tenant_does_not_block_others(client, two_tenants, platform_users, pool):
    """Security finding (HIGH): quantity * unit_price can overflow
    NUMERIC(12,2) inside generate_invoices(). Without the per-tenant
    BEGIN/EXCEPTION block in 0021_billing_invoices.sql, that overflow rolled
    back the ENTIRE job transaction -- including other tenants' invoices
    already inserted in the same run -- permanently blocking billing for the
    WHOLE platform (the poisoned tenant never advances next_invoice_date, so
    it qualifies again and breaks the job every day). This test confirms
    tenant B is invoiced normally even when tenant A overflows."""
    token = await login(client, platform_users["super_admin"]["email"])
    tenant_a = two_tenants["a"]["tenant_id"]
    tenant_b = two_tenants["b"]["tenant_id"]

    # unit_price_override and quantity are individually valid (each within
    # its own Pydantic bound), but their PRODUCT exceeds NUMERIC(12,2)
    # precision -- the combination a per-field bound cannot prevent.
    await _subscribe(client, token, tenant_a, custom_description="overflowing line", unit_price_override=9_999_999_999.99, quantity=100_000)
    plan_b = await _create_plan(client, token, unit_price=200.0)
    await _subscribe(client, token, tenant_b, plan_id=plan_b["id"], quantity=1)

    await _run_invoice_job(pool)

    resp_a = await client.get("/billing/invoices", params={"tenant_id": str(tenant_a)}, headers=auth_header(token))
    assert resp_a.json()["items"] == []  # tenant A: no invoice this cycle, retried tomorrow

    resp_b = await client.get("/billing/invoices", params={"tenant_id": str(tenant_b)}, headers=auth_header(token))
    items_b = resp_b.json()["items"]
    assert len(items_b) == 1
    assert items_b[0]["total"] == 200.0


async def test_invalid_status_filter_rejected_with_422(client, platform_users):
    token = await login(client, platform_users["super_admin"]["email"])
    resp = await client.get("/billing/invoices", params={"status": "not-a-real-status"}, headers=auth_header(token))
    assert resp.status_code == 422


async def test_tenant_admin_sees_only_own_invoices(client, two_tenants, platform_users, pool):
    token = await login(client, platform_users["super_admin"]["email"])
    plan = await _create_plan(client, token, unit_price=250.0)
    await _subscribe(client, token, two_tenants["a"]["tenant_id"], plan_id=plan["id"], quantity=1)
    await _subscribe(client, token, two_tenants["b"]["tenant_id"], plan_id=plan["id"], quantity=1)

    await _run_invoice_job(pool)

    tenant_a_token = await login(client, two_tenants["a"]["email"])
    resp = await client.get("/billing/invoices", headers=auth_header(tenant_a_token))
    assert resp.status_code == 200
    items = resp.json()["items"]
    assert len(items) == 1
    assert items[0]["tenant_id"] == str(two_tenants["a"]["tenant_id"])


async def test_tenant_admin_cannot_fetch_other_tenants_invoice_by_id(client, two_tenants, platform_users, pool):
    token = await login(client, platform_users["super_admin"]["email"])
    plan = await _create_plan(client, token, unit_price=250.0)
    await _subscribe(client, token, two_tenants["b"]["tenant_id"], plan_id=plan["id"], quantity=1)

    await _run_invoice_job(pool)

    b_invoice_id = (
        await client.get("/billing/invoices", params={"tenant_id": str(two_tenants["b"]["tenant_id"])}, headers=auth_header(token))
    ).json()["items"][0]["id"]

    tenant_a_token = await login(client, two_tenants["a"]["email"])
    resp = await client.get(f"/billing/invoices/{b_invoice_id}", headers=auth_header(tenant_a_token))
    assert resp.status_code == 404


async def test_tenant_operator_cannot_read_invoices(client, two_tenants, pool):
    """Unlike alarms/positions (require_non_driver), billing is narrower --
    not even tenant_operator can reach it."""
    from app import db as db_module
    from app.security import hash_password

    tenant_id = two_tenants["a"]["tenant_id"]
    email = f"operator-invoices-{uuid.uuid4().hex[:8]}@example.com"
    async with db_module.tenant_scoped_connection(pool, tenant_id=None, bypass=True) as conn:
        await conn.execute(
            "INSERT INTO users (tenant_id, email, password_hash, role) VALUES (%s, %s, %s, 'tenant_operator')",
            (tenant_id, email, hash_password(TEST_PASSWORD)),
        )
    token = await login(client, email)
    resp = await client.get("/billing/invoices", headers=auth_header(token))
    assert resp.status_code == 403


async def test_tenant_admin_cannot_create_promotion(client, two_tenants):
    token = await login(client, two_tenants["a"]["email"])
    resp = await client.post(
        "/billing/promotions",
        json={
            "tenant_id": str(two_tenants["a"]["tenant_id"]),
            "description": "x",
            "starts_at": date.today().isoformat(),
            "ends_at": date.today().isoformat(),
            "discount_type": "full_waiver",
        },
        headers=auth_header(token),
    )
    assert resp.status_code == 403


async def test_tenant_admin_cannot_read_promotions(client, two_tenants, platform_users):
    token = await login(client, platform_users["super_admin"]["email"])
    tenant_token = await login(client, two_tenants["a"]["email"])
    resp = await client.get("/billing/promotions", headers=auth_header(tenant_token))
    assert resp.status_code == 403


async def test_percentage_over_100_rejected(client, platform_users, two_tenants):
    token = await login(client, platform_users["super_admin"]["email"])
    resp = await client.post(
        "/billing/promotions",
        json={
            "tenant_id": str(two_tenants["a"]["tenant_id"]),
            "description": "x",
            "starts_at": date.today().isoformat(),
            "ends_at": date.today().isoformat(),
            "discount_type": "percentage",
            "discount_value": 150,
        },
        headers=auth_header(token),
    )
    assert resp.status_code == 422


async def test_ends_before_starts_rejected(client, platform_users, two_tenants):
    token = await login(client, platform_users["super_admin"]["email"])
    today = date.today()
    resp = await client.post(
        "/billing/promotions",
        json={
            "tenant_id": str(two_tenants["a"]["tenant_id"]),
            "description": "x",
            "starts_at": today.isoformat(),
            "ends_at": (today - timedelta(days=1)).isoformat(),
            "discount_type": "full_waiver",
        },
        headers=auth_header(token),
    )
    assert resp.status_code == 422


# ---------------------------------------------------------------------------
# Voiding invoices
# ---------------------------------------------------------------------------

async def test_bypass_can_void_issued_invoice(client, two_tenants, platform_users, pool):
    token = await login(client, platform_users["super_admin"]["email"])
    plan = await _create_plan(client, token, unit_price=100.0)
    tenant_id = two_tenants["a"]["tenant_id"]
    await _subscribe(client, token, tenant_id, plan_id=plan["id"], quantity=1)
    await _run_invoice_job(pool)

    invoice_id = (
        await client.get("/billing/invoices", params={"tenant_id": str(tenant_id)}, headers=auth_header(token))
    ).json()["items"][0]["id"]

    resp = await client.post(f"/billing/invoices/{invoice_id}/void", headers=auth_header(token))
    assert resp.status_code == 200
    assert resp.json()["status"] == "void"


async def test_cannot_void_already_paid_invoice(client, two_tenants, platform_users, pool):
    token = await login(client, platform_users["super_admin"]["email"])
    plan = await _create_plan(client, token, unit_price=100.0)
    tenant_id = two_tenants["a"]["tenant_id"]
    await _subscribe(client, token, tenant_id, plan_id=plan["id"], quantity=1)
    today = date.today()
    await client.post(
        "/billing/promotions",
        json={
            "tenant_id": str(tenant_id), "description": "free", "starts_at": today.isoformat(),
            "ends_at": (today + timedelta(days=30)).isoformat(), "discount_type": "full_waiver",
        },
        headers=auth_header(token),
    )
    await _run_invoice_job(pool)

    invoice_id = (
        await client.get("/billing/invoices", params={"tenant_id": str(tenant_id)}, headers=auth_header(token))
    ).json()["items"][0]["id"]
    assert (await client.get(f"/billing/invoices/{invoice_id}", headers=auth_header(token))).json()["status"] == "paid"

    resp = await client.post(f"/billing/invoices/{invoice_id}/void", headers=auth_header(token))
    assert resp.status_code == 409


async def test_tenant_admin_cannot_void_invoice(client, two_tenants, platform_users, pool):
    token = await login(client, platform_users["super_admin"]["email"])
    plan = await _create_plan(client, token, unit_price=100.0)
    tenant_id = two_tenants["a"]["tenant_id"]
    await _subscribe(client, token, tenant_id, plan_id=plan["id"], quantity=1)
    await _run_invoice_job(pool)

    invoice_id = (
        await client.get("/billing/invoices", params={"tenant_id": str(tenant_id)}, headers=auth_header(token))
    ).json()["items"][0]["id"]

    tenant_token = await login(client, two_tenants["a"]["email"])
    resp = await client.post(f"/billing/invoices/{invoice_id}/void", headers=auth_header(tenant_token))
    assert resp.status_code == 403
