-- Tenant self-service: branding (logo + name) and driver policy (meal break
-- window, max shift hours) configurable by the tenant_admin, plus alerts when
-- a driver deviates from that policy. HIGH-RISK change: widens the RLS UPDATE
-- policy on `tenants` and therefore requires an independent security review,
-- same as 0015_driver_shift_events.sql.

-- ---------------------------------------------------------------------------
-- 1. Self-service columns on tenants
-- ---------------------------------------------------------------------------

ALTER TABLE tenants
    ADD COLUMN display_name TEXT,
    ADD COLUMN logo_url TEXT,
    ADD COLUMN meal_break_window_start TIME,
    ADD COLUMN meal_break_window_end TIME,
    ADD COLUMN max_shift_hours NUMERIC(4, 1) CHECK (max_shift_hours > 0);

-- "No meal window" is an explicit valid state (both NULL), never only one side
-- configured, which would be ambiguous (from when? until when?).
ALTER TABLE tenants
    ADD CONSTRAINT tenants_meal_window_both_or_neither CHECK (
        (meal_break_window_start IS NULL) = (meal_break_window_end IS NULL)
    );

COMMENT ON COLUMN tenants.display_name IS 'Brand name shown instead of "OpenMDVR" in the nav rail and driver app once authenticated. NULL = use the default name.';
COMMENT ON COLUMN tenants.logo_url IS 'URL of an image already hosted by the tenant elsewhere. No file upload of its own (building storage just for a logo would be over-engineering).';
COMMENT ON COLUMN tenants.meal_break_window_start IS 'Allowed start time (UTC, time of day) to clock out for a meal. NULL together with meal_break_window_end = no restriction configured.';
COMMENT ON COLUMN tenants.meal_break_window_end IS 'Allowed end time (UTC, time of day) to clock out for a meal.';
COMMENT ON COLUMN tenants.max_shift_hours IS 'Maximum shift hours before generating an alert (driver_shift_alerts). NULL = no maximum. Tenant-wide policy, not per driver (v1).';

-- ---------------------------------------------------------------------------
-- 2. Widen tenants_update: RLS isolates by tenant, the role is enforced in the
--    API (same pattern as routes/vehicles/drivers, 0016/0014). Before this, NO
--    tenant_admin could update their own tenants row at the RLS level,
--    whatever the API did.
-- ---------------------------------------------------------------------------

DROP POLICY tenants_update ON tenants;
CREATE POLICY tenants_update ON tenants
    FOR UPDATE
    USING (app_bypass_rls() OR id = app_current_tenant_id())
    WITH CHECK (app_bypass_rls() OR id = app_current_tenant_id());

-- ---------------------------------------------------------------------------
-- 3. driver_shift_alerts: normal low-volume table (like
--    driver_shift_events/routes, NOT a hypertable), generated by the server
--    when a shift event deviates from the tenant policy. It never blocks the
--    real event that triggered it (alert-only); it is informational for the
--    admin, like alarms.
-- ---------------------------------------------------------------------------

CREATE TYPE driver_shift_alert_type AS ENUM ('meal_outside_window', 'shift_exceeds_max_hours');

CREATE TABLE driver_shift_alerts (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    driver_id       UUID NOT NULL REFERENCES drivers(id) ON DELETE RESTRICT,
    alert_type      driver_shift_alert_type NOT NULL,
    details         JSONB,
    occurred_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    acknowledged_at TIMESTAMPTZ,
    acknowledged_by UUID REFERENCES users(id) ON DELETE RESTRICT
);

CREATE INDEX driver_shift_alerts_tenant_id_idx ON driver_shift_alerts (tenant_id);
CREATE INDEX driver_shift_alerts_unacked_idx ON driver_shift_alerts (tenant_id, occurred_at DESC) WHERE acknowledged_at IS NULL;

CREATE TRIGGER driver_shift_alerts_enforce_driver_tenant
    BEFORE INSERT OR UPDATE ON driver_shift_alerts
    FOR EACH ROW EXECUTE FUNCTION enforce_driver_tenant_match();

COMMENT ON TABLE driver_shift_alerts IS 'Informational alert when a shift event deviates from the tenant policy (meal window, max hours). Never blocks the event that triggered it.';

ALTER TABLE driver_shift_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE driver_shift_alerts FORCE ROW LEVEL SECURITY;

-- Same dimension as driver_shift_events_select (0015): a driver would only see
-- their own alerts if some future endpoint exposed them (none does today;
-- /driver-shift-alerts requires require_non_driver); other roles see the whole
-- tenant.
CREATE POLICY driver_shift_alerts_select ON driver_shift_alerts
    FOR SELECT
    USING (
        app_bypass_rls()
        OR (
            tenant_id = app_current_tenant_id()
            AND (app_current_driver_id() IS NULL OR driver_id = app_current_driver_id())
        )
    );

-- INSERT: the API itself (clock_event in shifts.py) inserts the alert using the
-- connection already open for the driver's request, so WITH CHECK must
-- explicitly allow a driver session inserting an alert ABOUT THEMSELVES, not
-- only tenant_admin/bypass.
CREATE POLICY driver_shift_alerts_insert ON driver_shift_alerts
    FOR INSERT
    WITH CHECK (
        app_bypass_rls()
        OR (
            tenant_id = app_current_tenant_id()
            AND (app_current_driver_id() IS NULL OR driver_id = app_current_driver_id())
        )
    );

-- UPDATE: only to set acknowledged_at/acknowledged_by (acknowledge endpoint,
-- require_non_driver). Unlike SELECT/INSERT, a driver must NEVER update any row,
-- not even their own, so the condition is "app_current_driver_id() IS NULL"
-- (non-driver session) instead of repeating the "or matches own driver_id"
-- branch. Without this, the only real barrier would be require_non_driver in
-- the API: RLS isolating only by tenant while the role check lives 100% in the
-- API is a pattern that previously produced a real security finding.
CREATE POLICY driver_shift_alerts_update ON driver_shift_alerts
    FOR UPDATE
    USING (app_bypass_rls() OR (tenant_id = app_current_tenant_id() AND app_current_driver_id() IS NULL))
    WITH CHECK (app_bypass_rls() OR (tenant_id = app_current_tenant_id() AND app_current_driver_id() IS NULL));

CREATE POLICY driver_shift_alerts_delete ON driver_shift_alerts
    FOR DELETE USING (app_bypass_rls());

GRANT SELECT, INSERT, UPDATE, DELETE ON driver_shift_alerts TO app_user;
