-- Billing: promotions + invoices. See 0020_billing_catalog.sql for the
-- catalog/subscriptions.
--
-- Design decisions:
--
-- 1. tenant_promotions is a SEPARATE record, not a field on
--    tenant_subscription_items: "1 year free" is a period with start/end and
--    a discount type, not an attribute of a line. The invoicing job checks
--    active promotions when generating each invoice; when one ends, the NEXT
--    invoice is at normal price automatically, without support having to
--    remember anything.
-- 2. invoices/invoice_line_items SNAPSHOT the price when generated; they never
--    reference billing_plans/tenant_subscription_items live. If a plan's list
--    price changes later, old invoices are not altered (basic invoicing rule).
-- 3. Billing cycle per TENANT, not per line (decided in 0020_billing_catalog.sql
--    via tenants.billing_period/next_invoice_date): ALL active lines of a
--    tenant are invoiced together the same day, without proration.
-- 4. Not tax documents: these are INTERNAL invoices (a charge record of who
--    owes what), not legally certified fiscal invoices. Integrating with a tax
--    authority's e-invoicing system is a separate project.

CREATE TYPE promotion_discount_type AS ENUM ('full_waiver', 'percentage', 'fixed_amount');
CREATE TYPE invoice_status AS ENUM ('draft', 'issued', 'paid', 'overdue', 'void');

-- ---------------------------------------------------------------------------
-- tenant_promotions
-- ---------------------------------------------------------------------------
CREATE TABLE tenant_promotions (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    description     TEXT NOT NULL CHECK (btrim(description) <> ''),
    starts_at       DATE NOT NULL,
    ends_at         DATE NOT NULL,
    discount_type   promotion_discount_type NOT NULL,
    -- percentage: 0-100. fixed_amount: amount in the tenant's currency, capped
    -- at the real subtotal when applied (can never make the invoice negative).
    -- full_waiver: ignored, the discount is 100% of the subtotal.
    discount_value  NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (discount_value >= 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (ends_at >= starts_at),
    CHECK (discount_type <> 'percentage' OR discount_value <= 100)
);

CREATE INDEX tenant_promotions_tenant_id_idx ON tenant_promotions (tenant_id);
-- generate_invoices looks up active promotions for the period being invoiced;
-- this is the index that lookup uses.
CREATE INDEX tenant_promotions_active_window_idx ON tenant_promotions (tenant_id, starts_at, ends_at);

COMMENT ON TABLE tenant_promotions IS 'Per-tenant discount periods (free year/month, % or fixed amount). generate_invoices() applies them when generating each invoice, never retroactively.';

ALTER TABLE tenant_promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_promotions FORCE ROW LEVEL SECURITY;

-- Bypass-only in both directions. Unlike tenant_subscription_items, a tenant
-- does not need to see ITS promotions in detail (the discount is visible as
-- discount_total on its own invoice, which it can read). Same as billing_plans:
-- minimal exposed surface until there is a real business case.
CREATE POLICY tenant_promotions_select ON tenant_promotions FOR SELECT USING (app_bypass_rls());
CREATE POLICY tenant_promotions_insert ON tenant_promotions FOR INSERT WITH CHECK (app_bypass_rls());
CREATE POLICY tenant_promotions_update ON tenant_promotions FOR UPDATE USING (app_bypass_rls()) WITH CHECK (app_bypass_rls());
CREATE POLICY tenant_promotions_delete ON tenant_promotions FOR DELETE USING (app_bypass_rls());

GRANT SELECT, INSERT, UPDATE, DELETE ON tenant_promotions TO app_user;

-- ---------------------------------------------------------------------------
-- invoices + invoice_line_items
-- ---------------------------------------------------------------------------
CREATE TABLE invoices (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    period_start    DATE NOT NULL,
    period_end      DATE NOT NULL,
    issued_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    due_date        DATE NOT NULL,
    subtotal        NUMERIC(12, 2) NOT NULL CHECK (subtotal >= 0),
    discount_total  NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (discount_total >= 0),
    total           NUMERIC(12, 2) NOT NULL CHECK (total >= 0),
    currency        TEXT NOT NULL DEFAULT 'MXN',
    status          invoice_status NOT NULL DEFAULT 'issued',
    CHECK (period_end >= period_start)
);

CREATE INDEX invoices_tenant_id_idx ON invoices (tenant_id);
CREATE INDEX invoices_status_idx ON invoices (status);

COMMENT ON TABLE invoices IS 'INTERNAL charge record per tenant/cycle, generated by generate_invoices(). NOT a certified fiscal invoice. subtotal/discount_total/total are the SNAPSHOT of the real charge, never recomputed afterwards.';

ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices FORCE ROW LEVEL SECURITY;

-- SELECT: a tenant sees ITS OWN invoices (basis of "My billing"). Unlike
-- billing_plans/tenant_promotions, this IS information the customer must be
-- able to consult. Writes are bypass-only: in practice almost always done by
-- generate_invoices() (SECURITY DEFINER, bypasses RLS entirely); the policy only
-- covers the manual path (e.g. voiding an invoice by hand).
CREATE POLICY invoices_select ON invoices
    FOR SELECT USING (app_bypass_rls() OR tenant_id = app_current_tenant_id());
CREATE POLICY invoices_insert ON invoices FOR INSERT WITH CHECK (app_bypass_rls());
CREATE POLICY invoices_update ON invoices FOR UPDATE USING (app_bypass_rls()) WITH CHECK (app_bypass_rls());
CREATE POLICY invoices_delete ON invoices FOR DELETE USING (app_bypass_rls());

GRANT SELECT, INSERT, UPDATE, DELETE ON invoices TO app_user;

CREATE TABLE invoice_line_items (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_id  UUID NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    -- Denormalized on purpose (every business table carries tenant_id) so this
    -- table's RLS policy does not depend on a JOIN against invoices.
    tenant_id   UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    -- Text snapshot: plan name or the subscription line's custom description at
    -- invoicing time. Never a live FK to billing_plans/tenant_subscription_items.
    description TEXT NOT NULL,
    quantity    INTEGER NOT NULL CHECK (quantity > 0),
    unit_price  NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    subtotal    NUMERIC(12, 2) NOT NULL CHECK (subtotal >= 0)
);

CREATE INDEX invoice_line_items_invoice_id_idx ON invoice_line_items (invoice_id);
CREATE INDEX invoice_line_items_tenant_id_idx ON invoice_line_items (tenant_id);

COMMENT ON TABLE invoice_line_items IS 'SNAPSHOTTED lines of an issued invoice. description/unit_price are a copy from invoicing time and are never updated if the source plan changes later.';

ALTER TABLE invoice_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_line_items FORCE ROW LEVEL SECURITY;

CREATE POLICY invoice_line_items_select ON invoice_line_items
    FOR SELECT USING (app_bypass_rls() OR tenant_id = app_current_tenant_id());
CREATE POLICY invoice_line_items_insert ON invoice_line_items FOR INSERT WITH CHECK (app_bypass_rls());
CREATE POLICY invoice_line_items_update ON invoice_line_items FOR UPDATE USING (app_bypass_rls()) WITH CHECK (app_bypass_rls());
CREATE POLICY invoice_line_items_delete ON invoice_line_items FOR DELETE USING (app_bypass_rls());

GRANT SELECT, INSERT, UPDATE, DELETE ON invoice_line_items TO app_user;

-- ---------------------------------------------------------------------------
-- generate_invoices: daily job (same TimescaleDB add_job() mechanism as
-- enforce_gps_position_retention in 0019_gps_retention.sql, no new
-- infrastructure).
--
-- Two passes:
--   1. Bootstrap: a tenant with at least one active subscription line but NO
--      billing cycle started (next_invoice_date NULL since 0020) starts TODAY.
--      Grace for a new customer is given with promotions (full_waiver), not
--      an implicit cycle delay nobody configured.
--   2. Invoicing: every tenant whose next_invoice_date has arrived gets an
--      invoice with the SNAPSHOTTED subtotal of its active lines, the best
--      active promotion applied (if several overlap, the LARGEST discount wins;
--      should not happen in normal operation but is the safest resolution),
--      and its next_invoice_date advanced per billing_period. A tenant with no
--      active line (everything cancelled) does NOT get a $0 invoice; its cycle
--      is just advanced silently.
--
-- due_date = issue date + 15 days (NET 15). Fixed, not configurable yet; a
-- per-tenant or per-plan term would be a new tenants column, not a change here.
--
-- SECURITY DEFINER like enforce_gps_position_retention: app_user does have
-- direct GRANTs on these tables (unlike hypertables), but SECURITY DEFINER lets
-- the TimescaleDB scheduler run it regardless of the invoking role.
CREATE OR REPLACE PROCEDURE generate_invoices(job_id INT, config JSONB)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE
    t RECORD;
    v_period_start DATE;
    v_period_end DATE;
    v_next_date DATE;
    v_subtotal NUMERIC(12, 2);
    v_discount NUMERIC(12, 2);
    v_total NUMERIC(12, 2);
    v_status invoice_status;
    v_invoice_id UUID;
    v_has_active_items BOOLEAN;
BEGIN
    -- Alias "bt" (not "t"): the loop's RECORD variable below is named "t";
    -- plpgsql resolves an ambiguous reference to the variable rather than the
    -- table alias, and since "t" is not assigned yet here, it fails with
    -- "record t is not assigned yet".
    UPDATE tenants bt
    SET next_invoice_date = CURRENT_DATE
    WHERE bt.next_invoice_date IS NULL
      AND EXISTS (
          SELECT 1 FROM tenant_subscription_items si
          WHERE si.tenant_id = bt.id AND si.ended_at IS NULL
      );

    FOR t IN
        SELECT id, billing_period, next_invoice_date
        FROM tenants
        WHERE next_invoice_date IS NOT NULL AND next_invoice_date <= CURRENT_DATE
        FOR UPDATE
    LOOP
        -- Per-tenant BEGIN/EXCEPTION (implicit plpgsql SAVEPOINT). Security
        -- finding: without it, a NUMERIC(12,2) overflow in v_subtotal (e.g. an
        -- unreasonable quantity or price on ONE line of ONE tenant) rolls back
        -- the WHOLE job transaction, including other tenants' invoices already
        -- inserted in this run. Since that tenant's next_invoice_date does not
        -- advance either, it qualifies again and breaks the job EVERY following
        -- day, permanently blocking invoicing for the WHOLE platform. With this
        -- block, a tenant with out-of-range data is isolated (only it is
        -- retried, daily, until someone fixes its lines) without affecting
        -- anyone else.
        BEGIN
            v_period_start := t.next_invoice_date;
            v_next_date := CASE t.billing_period
                WHEN 'monthly' THEN (v_period_start + INTERVAL '1 month')::date
                WHEN 'semiannual' THEN (v_period_start + INTERVAL '6 months')::date
                WHEN 'annual' THEN (v_period_start + INTERVAL '1 year')::date
            END;
            v_period_end := v_next_date - 1;

            SELECT EXISTS (
                SELECT 1 FROM tenant_subscription_items si WHERE si.tenant_id = t.id AND si.ended_at IS NULL
            ) INTO v_has_active_items;

            IF NOT v_has_active_items THEN
                -- Nothing subscribed (everything cancelled): advance the cycle
                -- without a $0 invoice.
                UPDATE tenants SET next_invoice_date = v_next_date WHERE id = t.id;
                CONTINUE;
            END IF;

            SELECT COALESCE(SUM(si.quantity * COALESCE(si.unit_price_override, bp.unit_price)), 0)
            INTO v_subtotal
            FROM tenant_subscription_items si
            LEFT JOIN billing_plans bp ON bp.id = si.billing_plan_id
            WHERE si.tenant_id = t.id AND si.ended_at IS NULL;

            SELECT COALESCE(MAX(
                CASE p.discount_type
                    WHEN 'full_waiver' THEN v_subtotal
                    WHEN 'percentage' THEN ROUND(v_subtotal * p.discount_value / 100, 2)
                    WHEN 'fixed_amount' THEN LEAST(p.discount_value, v_subtotal)
                END
            ), 0)
            INTO v_discount
            FROM tenant_promotions p
            WHERE p.tenant_id = t.id AND p.starts_at <= v_period_end AND p.ends_at >= v_period_start;

            v_total := GREATEST(v_subtotal - v_discount, 0);
            v_status := CASE WHEN v_total = 0 THEN 'paid' ELSE 'issued' END;

            INSERT INTO invoices (tenant_id, period_start, period_end, due_date, subtotal, discount_total, total, status)
            VALUES (t.id, v_period_start, v_period_end, (CURRENT_DATE + INTERVAL '15 days')::date, v_subtotal, v_discount, v_total, v_status)
            RETURNING id INTO v_invoice_id;

            INSERT INTO invoice_line_items (invoice_id, tenant_id, description, quantity, unit_price, subtotal)
            SELECT v_invoice_id, t.id,
                   COALESCE(bp.name, si.custom_description),
                   si.quantity,
                   COALESCE(si.unit_price_override, bp.unit_price),
                   si.quantity * COALESCE(si.unit_price_override, bp.unit_price)
            FROM tenant_subscription_items si
            LEFT JOIN billing_plans bp ON bp.id = si.billing_plan_id
            WHERE si.tenant_id = t.id AND si.ended_at IS NULL;

            UPDATE tenants SET next_invoice_date = v_next_date WHERE id = t.id;
        EXCEPTION WHEN OTHERS THEN
            RAISE WARNING 'generate_invoices: failed to invoice tenant % (next_invoice_date not advanced, will retry tomorrow): %', t.id, SQLERRM;
        END;
    END LOOP;
END;
$$;

COMMENT ON PROCEDURE generate_invoices(INT, JSONB) IS
    'Daily job (add_job below): starts the cycle of new tenants (bootstrap) and generates the invoice of every tenant whose next_invoice_date has arrived, snapshotting subtotal/discount/total and advancing the cycle per billing_period.';

REVOKE ALL ON PROCEDURE generate_invoices(INT, JSONB) FROM PUBLIC;
GRANT EXECUTE ON PROCEDURE generate_invoices(INT, JSONB) TO app_user;

SELECT add_job('generate_invoices', '1 day');
